import fs from 'fs';
import path from 'path';
import Papa from 'papaparse';
import Dashboard from '@/components/Dashboard';

// Force dynamic rendering so it always reads the latest CSV data from the Python backend
export const dynamic = 'force-dynamic';

export default async function Home() {
  // Read the CSV generated by our Python backend
  // process.cwd() is the frontend directory
  const dataPath = path.join(process.cwd(), '../backend/data/ai_explained_discrepancies.csv');
  let records = [];

  try {
    if (fs.existsSync(dataPath)) {
      const file = fs.readFileSync(dataPath, 'utf8');
      const result = Papa.parse(file, { header: true, skipEmptyLines: true });
      records = result.data;
    } else {
      console.warn("CSV file not found. Have you run the backend generation script?");
    }
  } catch (err) {
    console.error("Could not load discrepancies data:", err);
  }

  return (
    <main className="min-h-screen bg-[#0a0a0a]">
      <Dashboard data={records} />
    </main>
  );
}
